AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API

Parameters:
  Project:
    Type: String
  Environment:
    Type: String

Resources:
  WebsiteSsrFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${Project}-WEBSITE-SSR-${Environment}'
      AutoPublishAlias: live
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs24.x
      MemorySize: 1024
      Architectures:
        - arm64
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Tracing: Active
    Metadata:
      BuildMethod: makefile

  WebsiteSsrIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId:
        Fn::ImportValue: !Sub '${Project}-${Environment}::ApiGateway::Website:Id'
      Description: Website SSR Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function}/invocations'
        - Function: !GetAtt WebsiteSsrFunctionAliaslive.AliasArn
      RequestParameters:
        "overwrite:path": "$request.path"
      PayloadFormatVersion: '2.0'

  WebsiteSsrRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId:
        Fn::ImportValue: !Sub '${Project}-${Environment}::ApiGateway::Website:Id'
      RouteKey: ANY /{proxy+}
      Target: !Sub "integrations/${WebsiteSsrIntegration}"

  ApiGatewayFunctionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref WebsiteSsrFunctionAliaslive
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub
        - "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*"
        - ApiGateway:
            Fn::ImportValue: !Sub '${Project}-${Environment}::ApiGateway::Website:Id'
